[package]

name = "02-gl-rs"
version = "0.1.0"
license = "ASL2"
authors = [ "Brendan Zabarauskas" ]

[[bin]]

name = "02-gl-rs"

[dependencies.gl]

git = "https://github.com/bjz/gl-rs.git"

[dependencies.glfw]

git = "https://github.com/bjz/glfw-rs.git"
