[package]

name = "00-basic-window"
version = "0.1.0"
license = "ASL2"
authors = [ "Brendan Zabarauskas" ]

[[bin]]

name = "00-basic-window"

[dependencies.glfw]

git = "https://github.com/bjz/glfw-rs.git"
